services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_telegram_bot
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - TZ=Europe/Berlin
      - NODES_EXCLUDE=[]
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      # --- Daten-Management ---
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=24
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./telegram_push:/home/node/.n8n-files/cat_previews # :ro entfernt!
